[build-system]
requires = [
    "setuptools>=68",
    "wheel"
]
build-backend = "setuptools.build_meta"


[project]
name = "graphtopic"
version = "0.0.0"

description = "Graph-based topic modeling"

keywords = [
    "topic-modeling",
    "graph",
    "nlp",
    "embeddings",
    "community-detection",
]

readme = "README.md"

requires-python = ">=3.11"

license = { text = "MIT" }

authors = [
    { name = "Mohsen Sahrayi" }
]

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
]


dependencies = []


[tool.setuptools]

package-dir = {"" = "src"}


[tool.setuptools.packages.find]

where = [
    "src"
]


[project.urls]

Homepage = "https://github.com/sahrayi/graphtopic"
Repository = "https://github.com/sahrayi/graphtopic"
Issues = "https://github.com/sahrayi/graphtopic/issues"
